// app/case-studies/[slug]/page.jsx
import ReactMarkdown from "react-markdown";
import fs from "fs";
import matter from "gray-matter";
import { cache } from "react";

export function generateStaticParams() {
	return fs.readdirSync("content/case-studies").map((file) => {
		return { slug: file.replace(".md", "") };
	});
}

const getProject = cache((slug) => {
	return matter(fs.readFileSync(`content/case-studies/${slug}.md`, ""));
});

export function generateMetadata({ params }) {
	const { data } = getProject(params.slug);
	return {
		title: data.title,
		description: data.summary,
		openGraph: {
			title: data.title,
			description: data.summary,
			images: data.image,
		},
	};
}

export default function ProjectPage({ params }) {
	const { data, content } = getProject(params.slug);
	return (
		<section className="flow">
			<h1>{data.title}</h1>
			<p>{data.client}</p>
			<hr aria-hidden="true" />
			<img
				src={data.image}
				alt={`${data.title} hero image`}
				width="1600"
				height="900"
				className="content-image"
			/>
			<ReactMarkdown className="flow">{content}</ReactMarkdown>
		</section>
	);
}

// pages/case-studies/[slug].vue
<script setup>
const route = useRoute();
const { data: project } = await useAsyncData(() =>
  queryContent("case-studies").where({ _path: route.path }).findOne()
);

useServerSeoMeta({
  title: project.value.title,
  description: project.value.summary,
});
</script>

<template>
  <section class="flow">
    <h1>{{ project.title }}</h1>
    <p>{{ project.client }}</p>
    <hr aria-hidden="true" />
    <nuxt-picture
      :src="project.image"
      :alt="`${project.title} hero image`"
      width="1600"
      height="900"
      class="content-image"
    />
    <nav aria-label="Table of contents" class="toc flow">
      <h2>Table of contents</h2>
      <ul v-if="project.body.toc && project.body.toc.links">
        <li v-for="link in project.body.toc.links" :key="link.text">
          <a :href="`#${link.id}`">
            {{ link.text }}
          </a>
        </li>
      </ul>
    </nav>
    <ContentRenderer class="flow" :value="project" />
  </section>
</template>
