// app/writing/[slug]/page.tsx
import Image from "next/image";
import { allPosts } from "~/.contentlayer/generated";

export function generateStaticParams() {
  return allPosts.map((post) => ({ slug: post.slug }));
}

export default function PostPage({ params }: { params: { slug: string } }) {
  const post = allPosts.filter((post) => post.slug === params.slug)[0];

  return (
    <section className="flow">
      <h1>{post.title}</h1>
      <p>
        {new Date(post.date).toLocaleDateString("en-gb", { dateStyle: "long" })}
      </p>
      <hr />
      <p>{post.summary}</p>
      <Image
        src={post.image}
        alt={`${post.title} hero image`}
        width={1600}
        height={900}
        className="content-image"
      />
      <article
        className="flow"
        dangerouslySetInnerHTML={{ __html: post.body.html }}
      />
    </section>
  );
}

// pages/writing/[slug].vue
<script setup>
const route = useRoute();
const { data: post } = await useAsyncData(() =>
  queryContent("writing").where({ _path: route.path }).findOne()
);

useServerSeoMeta({
  title: post.value.title,
  description: post.value.summary,
});
</script>

<template>
  <section class="flow">
    <h1>{{ post.title }}</h1>
    <p>
      {{
        new Date(post.date).toLocaleDateString("en-gb", { dateStyle: "long" })
      }}
    </p>
    <hr aria-hidden="true" />
    <nuxt-picture
      :src="post.image"
      :alt="`${post.title} hero image`"
      width="1600"
      height="900"
      class="content-image"
    />
    <nav aria-label="Table of contents" class="toc flow">
      <h2>Table of contents</h2>
      <ul v-if="post.body.toc && post.body.toc.links">
        <li v-for="link in post.body.toc.links" :key="link.text">
          <a :href="`#${link.id}`">
            {{ link.text }}
          </a>
        </li>
      </ul>
    </nav>
    <ContentRenderer class="flow" :value="post" />
  </section>
</template>
