// pages/writing/index.vue
<script setup>
const { data: posts } = await useAsyncData(() =>
  queryContent("writing").find()
);

useServerSeoMeta({
  title: "Writing",
});
</script>

<template>
  <section class="writing flow">
    <h1>Writing</h1>
    <ul class="flow">
      <li v-for="post in posts">
        <NuxtLink :to="post._path" class="flow">
          <h3>{{ post.title }}</h3>
          <p>
            {{
              new Date(post.date).toLocaleDateString("en-gb", {
                dateStyle: "long",
              })
            }}
          </p>
        </NuxtLink>
      </li>
    </ul>
  </section>
</template>

// app/writing/page.jsx
import Link from "next/link";
import fs from "fs";
import matter from "gray-matter";

export const metadata = {
	title: "Writing",
};

export default function WritingPage() {
	const posts = fs.readdirSync("content/writing").map((file) => {
		return {
			slug: file.replace(".md", ""),
			...matter(fs.readFileSync(`content/writing/${file}`, "utf-8")),
		};
	});
	return (
		<section className="writing flow">
			<h1>Writing</h1>
			<ul className="flow">
				{posts.map((post, index) => (
					<li key={index}>
						<Link href={`/writing/${post.slug}`} className="flow">
							<h3>{post.data.title}</h3>
							<p>
								{new Date(post.data.date).toLocaleDateString("en-gb", {
									dateStyle: "long",
								})}
							</p>
						</Link>
					</li>
				))}
			</ul>
		</section>
	);
}
