// src/components/Card.tsx
import Link from "next/link";

interface Props {
  item: {
    data: {
      title: string;
      image: string;
      imageAlt: string;
      client: string;
      role: string;
      summary: string;
    };
    slug: string;
  };
}

export default function Card({ item }: Props) {
  const { data, slug } = item;

  return (
    <Link href={`/work/${slug}`}>
      <a aria-label={`Link to ${data.title}`}>
        <article className='card'>
          <img
            src={data.image}
            alt={data.imageAlt}
            loading='lazy'
            decoding='async'
          />
          <div className='space-y'>
            <h3>{data.title}</h3>
            <div>
              <p>
                <span>Client: </span>
                {data.client}
              </p>
              <p>
                <span>Roles: </span>
                {data.role}
              </p>
            </div>
            <p>{data.summary}</p>
            <p>Read Case Study</p>
          </div>
        </article>
      </a>
    </Link>
  );
}

// src/lib/components/Card.svelte
<script lang="ts">
  export let item: {
    data: {
      title: string;
      image: string;
      imageAlt: string;
      client: string;
      role: string;
      summary: string;
    };
    slug: string;
  };
  const { data, slug } = item;
</script>

<a href={`/work/${slug}`} aria-label={`Link to ${data.title}`}>
  <article>
    <img src={data.image} alt={data.imageAlt} loading="lazy" decoding="async" />
    <div class="space-y">
      <h3>{data.title}</h3>
      <div>
        <p>
          <span>Client: </span>
          {data.client}
        </p>
        <p>
          <span>Roles: </span>
          {data.role}
        </p>
      </div>
      <p>{data.summary}</p>
      <p>Read Case Study</p>
    </div>
  </article>
</a>

<style>
  article {
    margin: 1.6rem 0;
    background-color: var(--clrWhite);
    border: 2px solid var(--clrBlue);
    border-radius: var(--brRadius);
    transition: var(--delay) ease;
  }
  article:hover {
    transform: scale(var(--scaleUp));
  }
  article > div {
    padding: 2rem;
  }
  article :is(span) {
    font-weight: var(--fwBold);
  }
</style>
